refactor: install

diff --git a/.rake/scripts/install b/.rake/scripts/install
--- a/.rake/scripts/install
+++ b/.rake/scripts/install
@@ -1,30 +1,29 @@
 #!/bin/env bash
 
-# TODO: rename from RAKEUP_INSTALL_DIR to RAKE_INSTALL_DIR
-RAKEUP_INSTALL_DIR="${RAKEUP_INSTALL_DIR:-$HOME/.rake/}"
+RAKE_INSTALL_DIR="${RAKE_INSTALL_DIR:-$HOME/.rake/}"
 
 curl -L https://raw.githubusercontent.com/m374-crypt0/rake/refs/heads/main/.rake/scripts/rake \
   --create-dirs \
-  --output "${RAKEUP_INSTALL_DIR}/rake" &&
-  chmod +x "${RAKEUP_INSTALL_DIR}rake" &&
+  --output "${RAKE_INSTALL_DIR}/rake" &&
+  chmod +x "${RAKE_INSTALL_DIR}rake" &&
   curl -L https://raw.githubusercontent.com/m374-crypt0/rake/refs/heads/main/.rake/scripts/rakeup \
     --create-dirs \
-    --output "${RAKEUP_INSTALL_DIR}/rakeup" &&
-  chmod +x "${RAKEUP_INSTALL_DIR}rakeup"
+    --output "${RAKE_INSTALL_DIR}/rakeup" &&
+  chmod +x "${RAKE_INSTALL_DIR}rakeup"
 
 case $SHELL in
 *bash)
-  if [[ ":$PATH:" != *":$RAKEUP_INSTALL_DIR:"* ]]; then
+  if [[ ":$PATH:" != *":$RAKE_INSTALL_DIR:"* ]]; then
     cat <<EOF >>"${HOME}/.bashrc"
 
 # rakeup
-export RAKEUP_INSTALL_DIR="$RAKEUP_INSTALL_DIR"
+export RAKEUP_INSTALL_DIR="$RAKE_INSTALL_DIR"
 export PATH="\${PATH}:\$RAKEUP_INSTALL_DIR"
 EOF
     echo "Added rakeup to your PATH. Source ${HOME}/.bashrc or start a new terminal session to use rakeup."
   fi
   ;;
 *)
-  echo "rakeup: cannot detect your shell. Do manually add $RAKEUP_INSTALL_DIR to your PATH" >&2
+  echo "rakeup: cannot detect your shell. Do manually add $RAKE_INSTALL_DIR to your PATH" >&2
   ;;
 esac
