feat: rake command
rake new is born, no new feature yet, preparing --force and --no-git-dir

diff --git a/.rake/scripts/rake b/.rake/scripts/rake
--- a/.rake/scripts/rake
+++ b/.rake/scripts/rake
@@ -6,14 +6,14 @@ ensure_directory_empty() {
     wc -c)"
 
   if [ "$c" -ne 0 ]; then
-    echo rake: call rake within an empty directory >&2
+    echo rake new error: current directory must be empty >&2
     return 1
   fi
 }
 
 ensure_not_git_repository() {
   if git status >/dev/null 2>&1; then
-    echo 'rake: do not rake within an existing git repository' >&2
+    echo 'rake new error: do not rake new within an existing git repository' >&2
     return 1
   fi
 }
@@ -86,10 +86,92 @@ init_rake_project() {
     echo .rake/.registered_sub >.gitignore
 }
 
-main() {
+print_man_page() {
+  cat <<EOF
+NAME
+  rake - because your mono-repo deserves better
+
+SYNOPSIS
+  rake <command> [<args>]
+
+DESCRIPTION
+  Think of rake as a single make to rule them all – it's the beautifully simple
+  solution that lets you stop wrestling with build orchestration and get back
+  to what actually matters: your code.
+
+  At its heart, rake is just a clever Makefile that knows how to talk to other
+  Makefiles. That's it. No fancy frameworks, no mysterious magic, no PhD
+  required. Just good old battle-tested make, git and bash doing what they've
+  done reliably for decades.
+
+RAKE COMMANDS
+  new
+    This command initializes a new rake project.
+    By default, you need to be in an empty directory and not within a git
+    repository.
+    After this command execution, your directory will contain all the necessary
+    to use rake that is:
+    - A .rake subdirectory containing all the necessary for rake to work
+    - A Makefile able to handle compound targets.
+
+RAKE NEW ARGS
+  -f, --force
+    Normally, attemtping to create a rake project within a non-empty directory
+    or within an empty directory being tracked by git is an error.
+    By specifying this option, a rake project will always be created in the
+    current directory
+
+  -n, --no-git-dir
+    Normally, creating a rake project also create a fresh git repository.
+    Specifying this option tells rake not to create a new git repository to
+    track this new rake project.
+EOF
+
+  return 1
+}
+
+print_generic_error_message() {
+  cat <<EOF >&2
+error: unrecognized command: <$1>
+
+  type rake without argument to read the manual
+EOF
+
+  return 1
+}
+
+is_unsupported_command() {
+  case "$1" in
+  new)
+    return 1
+    ;;
+  *)
+    return 0
+    ;;
+  esac
+}
+
+process_new() {
   ensure_directory_empty &&
     ensure_not_git_repository &&
     init_rake_project
 }
 
-main
+process_command() {
+  local command && command="$1" && shift &&
+    [ "$(type -t "process_$command")" = function ] &&
+    eval "process_$command"
+}
+
+main() {
+  [ $# -eq 0 ] &&
+    print_man_page ||
+    local command && command="$1" &&
+    is_unsupported_command "$command" &&
+    print_generic_error_message "$command" &&
+    return 1
+
+  process_command "$@"
+}
+
+main "$@"
